[workspace]
resolver = "2"
members = [
    "crates/rustpatcher-macros",
    "crates/rustpatcher",
]

default-members = [
    "crates/rustpatcher-macros",
    "crates/rustpatcher",
]

[profile.release]
panic = "abort"
debug = true
lto = "thin"